version: "3.3"

services:
  client:
    image: http-client.local
    container_name: client
    build:
      dockerfile: client.Dockerfile
    environment:
      - SERVER_URL=server:8006
    restart: "always"
    ports:
      - "80:80"
  
  server:
    image: http-server.local
    container_name: server
    build:
      dockerfile: server.Dockerfile
    ports:
      - "8006:8006"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 10M
